# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohOu81h45zT6C1QA2u8EZtj36wbTrZwJ
"""

import numpy as np
import matplotlib.pyplot as plt

# --- Параметры сигнала ---
N = 512  # количество отсчетов
low, high = -1, 1  # диапазон равномерного распределения

# Синтез сигнала x(k)
x = np.random.uniform(low, high, size=N)
k = np.arange(N)

# --- Функция равномерного квантования ---
def uniform_quantize(x, bits, x_min=None, x_max=None):
    """
    Равномерное (линейное) квантование с округлением до ближайшего уровня.
    - bits: число бит на отсчет (1..8)
    - возвращает массив квантованных значений той же длины, что x
    """
    L = 2 ** bits
    if x_min is None:
        x_min = np.min(x)
    if x_max is None:
        x_max = np.max(x)
    if x_max == x_min:
        return np.full_like(x, x_min)
    step = (x_max - x_min) / (L - 1)
    indices = np.round((x - x_min) / (x_max - x_min) * (L - 1)).astype(int)
    indices = np.clip(indices, 0, L - 1)
    q = x_min + indices * step
    return q

# --- График оригинального дискретного сигнала через step ---
plt.figure(figsize=(10, 3))
plt.plot(np.arange(N), x)
plt.title('Оригинальный дискретный сигнал x(k)')
plt.xlabel('k (отсчёт)')
plt.ylabel('x(k)')
plt.xlim(0, 100)  # показываем первые 100 отсчетов
plt.grid(True)
plt.tight_layout()
plt.show()


# --- Квантование и построение "ступенчатых" графиков для 1..8 бит ---
for bits in range(1, 9):
    xq = uniform_quantize(x, bits)

    plt.figure(figsize=(14, 5))
    plt.stairs(xq, edges, linewidth=2.0)
    plt.title(f'Квантованный сигнал: {bits} бит', fontsize=16)
    plt.xlabel('k (отсчёт)', fontsize=14)
    plt.ylabel('x_q(k)', fontsize=14)
    plt.xlim(0, 100)   # увеличиваем первые 100 отсчётов
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# --- Задания 3 и 4: Ошибка квантования и SNR ---

for bits in bits_list:
    xq = uniform_quantize(x, bits, x_min=np.min(x), x_max=np.max(x))
    step = (np.max(x) - np.min(x)) / (2**bits - 1)

    e = x - xq
    mse_s = np.mean(e**2)
    mse_sample.append(mse_s)
    mse_th = (step**2) / 12.0
    mse_theoretical.append(mse_th)
    snr_sample_db.append(20 * np.log10(signal_power / mse_s))
    snr_theoretical_db.append(20 * np.log10(((R**2)/12.0) / mse_th))


# --- График MSE ---
plt.figure(figsize=(8,4))
plt.plot(bits_list, mse_sample, marker='o', label='Выборочное MSE')
plt.plot(bits_list, mse_theoretical, marker='s', linestyle='--', label='Теоретическая Δ²/12')
plt.yscale('log')
plt.grid(True, which='both', ls=':')
plt.xlabel('Число бит на отсчёт')
plt.ylabel('MSE')
plt.title('MSE квантования: выборочные и теоретические значения')
plt.xticks(bits_list)
plt.legend()
plt.tight_layout()
plt.show()

# --- График SNR ---
plt.figure(figsize=(8,4))
plt.plot(bits_list, snr_sample_db, marker='o', label='SNR (выборочный)')
plt.plot(bits_list, snr_theoretical_db, marker='s', linestyle='--', label='SNR (теоретический)')
plt.grid(True)
plt.xlabel('Число бит на отсчёт')
plt.ylabel('SNR, dB')
plt.title('Зависимость SNR от числа бит')
plt.xticks(bits_list)
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# === Параметры варианта ===
v = 1               # номер варианта (замени на свой!)
m = v               # мат. ожидание
sigma = v + 1       # стандартное отклонение
N = 500             # число отсчётов

# === 5. Генерация сигнала с нормальным распределением ===
y = np.random.normal(loc=m, scale=sigma, size=N)
k = np.arange(N)

plt.figure(figsize=(10, 4))
plt.plot(k[:100], y[:100], marker='o', linestyle='-', markersize=3)
plt.title(f'Случайный сигнал y(k) ~ N(m={m}, σ={sigma}) (первые 100 отсчётов)')
plt.xlabel('k (отсчёт)')
plt.ylabel('y(k)')
plt.grid(True)
plt.tight_layout()
plt.show()

# === Табличные параметры Ллойда-Макса для N(0,1) ===
lm_tables = {
    1: {"t": np.array([-np.inf, 0, np.inf]),
        "d": np.array([-0.7979, 0.7979])},
    2: {"t": np.array([-np.inf, -0.9816, 0, 0.9816, np.inf]),
        "d": np.array([-1.5104, -0.4528, 0.4528, 1.5104])},
    3: {"t": np.array([-np.inf, -1.7479, -1.05, -0.5005, 0, 0.5005, 1.05, 1.7479, np.inf]),
        "d": np.array([-2.1519, -1.3439, -0.756, -0.2451, 0.2451, 0.756, 1.3439, 2.1519])},
    4: {"t": np.array([-np.inf, -2.4008, -1.8435, -1.4371, -1.0993, -0.7995,
                       -0.5224, -0.2582, 0, 0.2582, 0.5224, 0.7995, 1.0993,
                       1.4371, 1.8435, 2.4008, np.inf]),
        "d": np.array([-2.7326, -2.069, -1.618, -1.2562, -0.9423, -0.6568,
                       -0.388, -0.1284, 0.1284, 0.388, 0.6568, 0.9423,
                       1.2562, 1.618, 2.069, 2.7326])}
}

# === 6. Масштабирование параметров под N(m, σ²) ===
for bits in range(1, 5):
    t_std = lm_tables[bits]["t"]
    d_std = lm_tables[bits]["d"]

    t_scaled = t_std * sigma + m
    d_scaled = d_std * sigma + m

    print(f"\nПараметры Ллойда-Макса для {bits} бит:")
    print("Пороги t'_k:", np.round(t_scaled, 4))
    print("Уровни d'_k:", np.round(d_scaled, 4))

# === 7–8. Оптимальное квантование, MSE и SNR ===
mse_lm = []
snr_lm = []

for bits in range(1, 5):
    t_scaled = lm_tables[bits]["t"] * sigma + m
    d_scaled = lm_tables[bits]["d"] * sigma + m

    yq = np.empty_like(y)
    for i in range(len(d_scaled)):
        left = t_scaled[i]
        right = t_scaled[i + 1]
        mask = (y > left) & (y <= right)
        yq[mask] = d_scaled[i]

    e = y - yq
    mse = np.mean(e ** 2)
    signal_power = np.mean(y ** 2)
    snr_db = 10 * np.log10(signal_power / mse)

    mse_lm.append(mse)
    snr_lm.append(snr_db)

# === 9. Равномерное квантование ===
def uniform_quantize(x, bits, x_min=None, x_max=None):
    L = 2 ** bits
    if x_min is None:
        x_min = np.min(x)
    if x_max is None:
        x_max = np.max(x)
    step = (x_max - x_min) / (L - 1)
    indices = np.round((x - x_min) / (x_max - x_min) * (L - 1)).astype(int)
    indices = np.clip(indices, 0, L - 1)
    return x_min + indices * step

mse_uni = []
snr_uni = []

for bits in range(1, 5):
    yq = uniform_quantize(y, bits)
    e = y - yq
    mse = np.mean(e ** 2)
    signal_power = np.mean(y ** 2)
    snr_db = 10 * np.log10(signal_power / mse)

    mse_uni.append(mse)
    snr_uni.append(snr_db)

# === Графики сравнения ===
bits_range = np.arange(1, 5)

plt.figure(figsize=(10, 5))
plt.semilogy(bits_range, mse_lm, 'o-', label='Lloyd–Max')
plt.semilogy(bits_range, mse_uni, 's--', label='Равномерное')
plt.title('Ошибка квантования (MSE)')
plt.xlabel('Число бит на отсчёт')
plt.ylabel('MSE (лог. шкала)')
plt.grid(True, which="both")
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(bits_range, snr_lm, 'o-', label='Lloyd–Max')
plt.plot(bits_range, snr_uni, 's--', label='Равномерное')
plt.title('SNR (дБ)')
plt.xlabel('Число бит на отсчёт')
plt.ylabel('SNR (дБ)')
plt.grid(True)
plt.legend()
plt.show()

