# -*- coding: utf-8 -*-
"""Untitled81.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1An0e-qEGTWmt_geZI13a_0kP0LnTJqtq
"""

#Задание1
import numpy as np
import matplotlib.pyplot as plt

# filter parameters (вариант 1)
w_p = [0, 0.60 * np.pi]
M = 5                 # M


w_j = np.pi * (np.arange(0, M + 1) + 0.5) / (M + 1)


K_d = ((w_j >= w_p[0]) & (w_j <= w_p[1])).astype(float)

h = np.zeros(M + 1)
for k in range(M + 1):
    h[M - k] = (1.0 / (M + 1)) * np.sum(
        K_d * np.cos(np.pi * k * (np.arange(0, M + 1) + 0.5) / (M + 1))
    )

w = np.arange(0, 2 * np.pi, 0.001)


A = h[M] + 2 * np.sum([
    h[M - k] * np.cos(w * k) for k in range(1, M + 1)
], axis=0)


K_mag = np.abs(A)
K_phase = -M * w + np.angle(A)


ideal_A = np.zeros_like(w)

ideal_A[(w <= w_p[1]) | (w >= 2*np.pi - w_p[1])] = 1.0
ideal_phase = -M * w

fig, axs = plt.subplots(3, 1, figsize=(10, 9))

# 1) АЧХ — линейный масштаб
axs[0].plot(w, K_mag, label='Синтезированный')
axs[0].plot(w, ideal_A, 'r--', label='Идеальный')
axs[0].set_ylabel(r'$|K(\omega)|$')
axs[0].set_title('АЧХ')
axs[0].grid(True)
axs[0].legend()

# 2) АЧХ — децибелы
K_mag_db = 20 * np.log10(np.maximum(K_mag, 1e-7))
ideal_A_db = 20 * np.log10(np.maximum(ideal_A, 1e-7))
axs[1].plot(w, K_mag_db, label='Синтезированный')
axs[1].plot(w, ideal_A_db, 'r--', label='Идеальный')
axs[1].set_ylabel(r'$20\log_{10}|K(\omega)|$, дБ')
axs[1].set_title('АЧХ (децибелы)')
axs[1].grid(True)
axs[1].legend()

# 3) ФЧХ
axs[2].plot(w, K_phase, label='Синтезированный')
axs[2].plot(w, ideal_phase, 'r--', label='Идеальный (линейная)')
axs[2].set_xlabel(r'$\omega$, рад/отсчёт')
axs[2].set_ylabel(r'$\angle K(\omega)$, рад')
axs[2].set_title('ФЧХ')
axs[2].grid(True)
axs[2].legend()

plt.tight_layout()
plt.show()

#Задание2
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize

# -------------------------------
# filter parameters (вариант 1)
w_p = [0, 0.60 * np.pi]   # bandwidth — полоса пропускания
w_s = [0.80 * np.pi, np.pi]  # stopband — полоса подавления
M = 5                      # M
# -------------------------------

def syntez(x, w_p, w_s, M):
    """
    Возвращает ошибку E и коэффициенты h (формула (3), (4.8))
    """
    # Узлы частотной выборки: ω_j = π·(j + 0.5)/(M + 1), j = 0..M
    j = np.arange(0, M + 1)
    w_j = np.pi * (j + 0.5) / (M + 1)

    # Флаги принадлежности узлов полосам
    flag_p = (w_j >= w_p[0]) & (w_j <= w_p[1])
    flag_s = (w_j >= w_s[0]) & (w_j <= w_s[1])
    flag_t = ~(flag_p | flag_s)  # переходная зона

    # Желаемая АЧХ на узлах
    K_d = np.zeros(M + 1)
    K_d[flag_p] = 1.0
    K_d[flag_s] = 0.0
    K_d[flag_t] = x

    # Расчёт коэффициентов (формула 4.8)
    h = np.zeros(M + 1)
    for k in range(M + 1):
        cos_term = np.cos(np.pi * k * (j + 0.5) / (M + 1))
        h[M - k] = (1.0 / (M + 1)) * np.sum(K_d * cos_term)

    # Плотная сетка частот для оценки ошибки
    w_eval = np.linspace(0, np.pi, 2000)

    # АЧХ A(ω) по формуле (4.7):
    A_w = h[M] + 2 * np.sum([
        h[M - k] * np.cos(w_eval * k) for k in range(1, M + 1)
    ], axis=0)

    # Ошибка E — максимум уклонений в Ωp и Ωs (формула 3)
    err_p = np.abs(A_w[(w_eval >= w_p[0]) & (w_eval <= w_p[1])] - 1.0)
    err_s = np.abs(A_w[(w_eval >= w_s[0]) & (w_eval <= w_s[1])])
    E = np.max(np.concatenate([err_p, err_s]))

    return E, h




# Узлы частотной выборки
w_j = np.pi * (np.arange(0, M + 1) + 0.5) / (M + 1)

# Флаги полос
flag_p = (w_j > w_p[0]) & (w_j <= w_p[1])
flag_s = (w_j >= w_s[0]) & (w_j < w_s[1])
flag_t = ~(flag_p | flag_s)
num_t = np.sum(flag_t)

# Начальное приближение: линейная интерполяция от 1 до 0
x0 = np.linspace(1.0, 0.0, num_t) if num_t > 0 else np.array([])

# Оптимизация
result = optimize.fmin(lambda t: syntez(t, w_p, w_s, M)[0], x0=x0, disp=False)
Er, h = syntez(result, w_p, w_s, M)

print(f"Минимальная ошибка E = {Er:.6f}")
print("Коэффициенты h =", h)


w = np.arange(0, 2 * np.pi, 0.001)

# A(ω) — амплитудная функция (формула 4.7)
A = h[M] + 2 * np.sum([
    h[M - k] * np.cos(w * k) for k in range(1, M + 1)
], axis=0)


K_mag = np.abs(A)
K_phase = -M * w + np.angle(A)


# Идеальный фильтр для сравнения
ideal_A = np.zeros_like(w)
ideal_A[(w <= w_p[1]) | (w >= 2*np.pi - w_p[1])] = 1.0
ideal_phase = -M * w



fig, axs = plt.subplots(3, 1, figsize=(10, 9))

axs[0].plot(w, K_mag, label='Синтезированный (task2)')
axs[0].plot(w, ideal_A, 'r--', label='Идеальный')
axs[0].set_ylabel(r'$|K(\omega)|$')
axs[0].set_title('АЧХ (линейный масштаб)')
axs[0].grid(True)
axs[0].legend()

K_mag_db = 20 * np.log10(np.maximum(K_mag, 1e-7))
ideal_A_db = 20 * np.log10(np.maximum(ideal_A, 1e-7))
axs[1].plot(w, K_mag_db, label='Синтезированный (task2)')
axs[1].plot(w, ideal_A_db, 'r--', label='Идеальный')
axs[1].set_ylabel(r'$20\log_{10}|K(\omega)|$, дБ')
axs[1].set_title('АЧХ в дБ')
axs[1].grid(True)
axs[1].legend()

axs[2].plot(w, K_phase, label='Синтезированный (task2)')
axs[2].plot(w, ideal_phase, 'r--', label='Идеальный (линейная)')
axs[2].set_xlabel(r'$\omega$, рад/отсчёт')
axs[2].set_ylabel(r'$\angle K(\omega)$, рад')
axs[2].set_title('ФЧХ')
axs[2].grid(True)
axs[2].legend()

plt.tight_layout()
plt.show()

#Задание3
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize

# --- Параметры фильтра (вариант 1) ---
w_p = [0, 0.60 * np.pi]      # Полоса пропускания
w_s = [0.80 * np.pi, np.pi]  # Полоса подавления
delta_p = 0.0125              # Допуск в Ωp
delta_s = 0.015               # Допуск в Ωs

def syntez_with_error(x, w_p, w_s, M):
    w_j = np.pi * (np.arange(0, M + 1) + 0.5) / (M + 1)

    K_d = np.zeros(M + 1)
    flag_p = (w_j >= w_p[0]) & (w_j <= w_p[1])
    K_d[flag_p] = 1.0
    flag_s = (w_j >= w_s[0]) & (w_j <= w_s[1])
    K_d[flag_s] = 0.0
    flag_t = (~flag_p) & (~flag_s)
    K_d[flag_t] = x

    h = np.zeros(M + 1)
    for k in range(M + 1):
        h[M - k] = (1.0 / (M + 1)) * np.sum(
            K_d * np.cos(np.pi * k * (np.arange(0, M + 1) + 0.5) / (M + 1))
        )

    w_eval = np.linspace(0, np.pi, 1024)
    A_w = h[M] + 2 * np.sum([
        h[M - k] * np.cos(w_eval * k) for k in range(1, M + 1)
    ], axis=0)

    err_p = np.abs(A_w[(w_eval >= w_p[0]) & (w_eval <= w_p[1])] - 1.0)
    err_s = np.abs(A_w[(w_eval >= w_s[0]) & (w_eval <= w_s[1])])
    max_err_p = np.max(err_p) if len(err_p) > 0 else 0
    max_err_s = np.max(err_s) if len(err_s) > 0 else 0
    E = max(max_err_p, max_err_s)

    return E, h, max_err_p, max_err_s

# --- Поиск минимального M ---
M_start = 5
M_current = M_start
found = False

while not found:
    w_j = np.pi * (np.arange(0, M_current + 1) + 0.5) / (M_current + 1)
    flag_p = (w_j >= w_p[0]) & (w_j <= w_p[1])
    flag_s = (w_j >= w_s[0]) & (w_j <= w_s[1])
    flag_t = (~flag_p) & (~flag_s)
    x0 = np.linspace(1.0, 0.0, np.sum(flag_t)) if np.sum(flag_t) > 0 else np.array([])

    result = optimize.fmin(lambda t: syntez_with_error(t, w_p, w_s, M_current)[0], x0=x0, disp=False)
    E_opt, h_opt, max_err_p, max_err_s = syntez_with_error(result, w_p, w_s, M_current)

    if max_err_p <= delta_p and max_err_s <= delta_s:
        found = True
        M_min = M_current
        h_final = h_opt
    else:
        M_current += 1

print(f"\n--- Минимальный порядок фильтра: M = {M_min}, N = {2 * M_min} ---")

# === СОХРАНЯЕМ h_opt ДЛЯ ЗАДАНИЯ 4 ===
h_opt = h_final.copy()  # h_opt = [h(0), h(1), ..., h(M)]
print("\n>>> КОЭФФИЦИЕНТЫ ДЛЯ ЗАДАНИЯ 4 (скопируйте в task4.py):")
print("h_opt = np.array([")
print("    " + ", ".join([f"{val:.6f}" for val in h_opt]))
print("])")
print(f"M_min = {M_min}")

# --- Построение графиков (как в вашей программе, без изменений) ---
w = np.linspace(0, 2 * np.pi, 2001)
A_w = h_final[M_min] + 2 * np.sum([
    h_final[M_min - k] * np.cos(w * k) for k in range(1, M_min + 1)
], axis=0)
K_w = np.exp(-1j * w * M_min) * A_w
magnitude = np.abs(K_w)
phase = np.angle(K_w)

ideal_mag = np.zeros_like(w)
ideal_mag[(w <= w_p[1]) | (w >= 2*np.pi - w_p[1])] = 1.0
ideal_mag[(w >= w_s[0]) & (w <= 2*np.pi - w_s[0])] = 0.0

fig, axs = plt.subplots(3, 1, figsize=(10, 10))
axs[0].plot(w, magnitude, label='Синтезированный')
axs[0].plot(w, ideal_mag, 'r--', label='Идеальный')
axs[0].set_ylabel(r'$|K(\omega)|$'); axs[0].grid(); axs[0].legend()
axs[1].plot(w, 20*np.log10(np.maximum(magnitude,1e-7)), label='Синтезированный')
axs[1].plot(w, 20*np.log10(np.maximum(ideal_mag,1e-7)), 'r--', label='Идеальный')
axs[1].set_ylabel('дБ'); axs[1].grid(); axs[1].legend()
axs[2].plot(w, phase, label='Синтезированный')
axs[2].plot(w, -M_min * w, 'r--', label='Идеальный (линейная)')
axs[2].set_xlabel(r'$\omega$'); axs[2].set_ylabel('рад'); axs[2].grid(); axs[2].legend()
for ax in axs: ax.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
ax.set_xticklabels(['0', r'$\pi/2$', r'$\pi$', r'$3\pi/2$', r'$2\pi$'])
plt.tight_layout()
plt.show()

#Задание4
import numpy as np
from scipy import signal

M = 11
b = np.array([
    -0.004102, 0.000937, 0.009466, -0.017117, 0.008421, 0.019461, -0.047273, 0.039829, 0.028003, -0.143908, 0.255606, 0.698131
])
omega_x = [0.30 * np.pi, 0.50 * np.pi]

for wx in omega_x:
    x = np.sin(wx * np.arange(200))
    y = signal.lfilter(b, [1.0], x)
    corr = np.correlate(y[M:-M], x[M:-M], mode='full')
    lag = np.argmax(corr) - (len(x) - 2 * M - 1)
    print(int(round(lag)))

#Задание5
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from scipy.signal import lfilter

# --- Данные из задания 3 (вариант 1, M = 11) ---
M = 11
h = np.array([
    0.000410, 0.002312, 0.008731, 0.022474, 0.045046,
    0.075432, 0.110186, 0.143762, 0.169099, 0.178615,
    0.166147, 0.128087
])
b = np.concatenate([h[::-1], h[1:]])

# --- Загрузка изображения (замените путь) ---
img = np.array(Image.open(r"C:\Users\vlad-\OneDrive\Документы\Учеба МИЭТ\3 курс\ЦОС\Задание 1\var1.png").convert('L'), dtype=float)

# --- Фильтрация: сначала строки, потом столбцы ---
filtered = np.apply_along_axis(lambda x: lfilter(b, [1.0], x), axis=1, arr=img)
filtered = np.apply_along_axis(lambda x: lfilter(b, [1.0], x), axis=0, arr=filtered)

# --- Вывод ---
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title('Исходное изображение')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(filtered, cmap='gray')
plt.title('Отфильтрованное изображение')
plt.axis('off')

plt.tight_layout()
plt.show()